version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-curso
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisdb2024
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  curso:
    build:
      context: .
    container_name: curso-container
    ports:
      - "8005:8002"
    environment:
      spring.datasource.url: jdbc:mysql://mysql-db:3306/sisdb2024
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      - mysql-db
volumes:
  db_data:
